package tesis.com.py.sisgourmetmobile.entities;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import tesis.com.py.sisgourmetmobile.entities.PersonDao;
import tesis.com.py.sisgourmetmobile.entities.QualificationDao;
import tesis.com.py.sisgourmetmobile.entities.DrinksDao;
import tesis.com.py.sisgourmetmobile.entities.LunchDao;
import tesis.com.py.sisgourmetmobile.entities.OrderDao;
import tesis.com.py.sisgourmetmobile.entities.ProviderDao;
import tesis.com.py.sisgourmetmobile.entities.GarnishDao;
import tesis.com.py.sisgourmetmobile.entities.CommentsDao;
import tesis.com.py.sisgourmetmobile.entities.UserDao;
import tesis.com.py.sisgourmetmobile.entities.ProviderRatingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        PersonDao.createTable(db, ifNotExists);
        QualificationDao.createTable(db, ifNotExists);
        DrinksDao.createTable(db, ifNotExists);
        LunchDao.createTable(db, ifNotExists);
        OrderDao.createTable(db, ifNotExists);
        ProviderDao.createTable(db, ifNotExists);
        GarnishDao.createTable(db, ifNotExists);
        CommentsDao.createTable(db, ifNotExists);
        UserDao.createTable(db, ifNotExists);
        ProviderRatingDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        PersonDao.dropTable(db, ifExists);
        QualificationDao.dropTable(db, ifExists);
        DrinksDao.dropTable(db, ifExists);
        LunchDao.dropTable(db, ifExists);
        OrderDao.dropTable(db, ifExists);
        ProviderDao.dropTable(db, ifExists);
        GarnishDao.dropTable(db, ifExists);
        CommentsDao.dropTable(db, ifExists);
        UserDao.dropTable(db, ifExists);
        ProviderRatingDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(PersonDao.class);
        registerDaoClass(QualificationDao.class);
        registerDaoClass(DrinksDao.class);
        registerDaoClass(LunchDao.class);
        registerDaoClass(OrderDao.class);
        registerDaoClass(ProviderDao.class);
        registerDaoClass(GarnishDao.class);
        registerDaoClass(CommentsDao.class);
        registerDaoClass(UserDao.class);
        registerDaoClass(ProviderRatingDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
