package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DRINKS".
 */
public class Drinks {

    private Long id;
    private Integer drinkId;
    private String description;
    private Integer currentStock;
    private Integer priceUnit;
    private String provider;

    public Drinks() {
    }

    public Drinks(Long id) {
        this.id = id;
    }

    public Drinks(Long id, Integer drinkId, String description, Integer currentStock, Integer priceUnit, String provider) {
        this.id = id;
        this.drinkId = drinkId;
        this.description = description;
        this.currentStock = currentStock;
        this.priceUnit = priceUnit;
        this.provider = provider;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDrinkId() {
        return drinkId;
    }

    public void setDrinkId(Integer drinkId) {
        this.drinkId = drinkId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getCurrentStock() {
        return currentStock;
    }

    public void setCurrentStock(Integer currentStock) {
        this.currentStock = currentStock;
    }

    public Integer getPriceUnit() {
        return priceUnit;
    }

    public void setPriceUnit(Integer priceUnit) {
        this.priceUnit = priceUnit;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

}
