package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DRINKS".
 */
public class Drinks {

    private Long id;
    private String description;
    private Integer currentStock;
    private Integer minimunStock;
    private Integer priceUnit;
    private String provider;

    public Drinks() {
    }

    public Drinks(Long id) {
        this.id = id;
    }

    public Drinks(Long id, String description, Integer currentStock, Integer minimunStock, Integer priceUnit, String provider) {
        this.id = id;
        this.description = description;
        this.currentStock = currentStock;
        this.minimunStock = minimunStock;
        this.priceUnit = priceUnit;
        this.provider = provider;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getCurrentStock() {
        return currentStock;
    }

    public void setCurrentStock(Integer currentStock) {
        this.currentStock = currentStock;
    }

    public Integer getMinimunStock() {
        return minimunStock;
    }

    public void setMinimunStock(Integer minimunStock) {
        this.minimunStock = minimunStock;
    }

    public Integer getPriceUnit() {
        return priceUnit;
    }

    public void setPriceUnit(Integer priceUnit) {
        this.priceUnit = priceUnit;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

}
