package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GARNISH".
 */
public class Garnish {

    private Long id;
    private Long lunchId;
    private String description;
    private Integer unitPrice;

    public Garnish() {
    }

    public Garnish(Long id) {
        this.id = id;
    }

    public Garnish(Long id, Long lunchId, String description, Integer unitPrice) {
        this.id = id;
        this.lunchId = lunchId;
        this.description = description;
        this.unitPrice = unitPrice;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getLunchId() {
        return lunchId;
    }

    public void setLunchId(Long lunchId) {
        this.lunchId = lunchId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Integer unitPrice) {
        this.unitPrice = unitPrice;
    }

}
