package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GARNISH".
 */
public class Garnish {

    private Long id;
    private Integer priceUnit;
    private String description;

    public Garnish() {
    }

    public Garnish(Long id) {
        this.id = id;
    }

    public Garnish(Long id, Integer priceUnit, String description) {
        this.id = id;
        this.priceUnit = priceUnit;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPriceUnit() {
        return priceUnit;
    }

    public void setPriceUnit(Integer priceUnit) {
        this.priceUnit = priceUnit;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
