package tesis.com.py.sisgourmetmobile.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import tesis.com.py.sisgourmetmobile.entities.Lunch;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LUNCH".
*/
public class LunchDao extends AbstractDao<Lunch, Long> {

    public static final String TABLENAME = "LUNCH";

    /**
     * Properties of entity Lunch.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PrincipalMenuCode = new Property(1, Integer.class, "principalMenuCode", false, "PRINCIPAL_MENU_CODE");
        public final static Property PriceUnit = new Property(2, Integer.class, "priceUnit", false, "PRICE_UNIT");
        public final static Property MainMenuDescription = new Property(3, String.class, "mainMenuDescription", false, "MAIN_MENU_DESCRIPTION");
        public final static Property ProviderId = new Property(4, Integer.class, "providerId", false, "PROVIDER_ID");
        public final static Property MenuDate = new Property(5, String.class, "menuDate", false, "MENU_DATE");
        public final static Property RatingMenu = new Property(6, Double.class, "ratingMenu", false, "RATING_MENU");
        public final static Property ImageMenu = new Property(7, byte[].class, "imageMenu", false, "IMAGE_MENU");
    };


    public LunchDao(DaoConfig config) {
        super(config);
    }
    
    public LunchDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LUNCH\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PRINCIPAL_MENU_CODE\" INTEGER," + // 1: principalMenuCode
                "\"PRICE_UNIT\" INTEGER," + // 2: priceUnit
                "\"MAIN_MENU_DESCRIPTION\" TEXT," + // 3: mainMenuDescription
                "\"PROVIDER_ID\" INTEGER," + // 4: providerId
                "\"MENU_DATE\" TEXT," + // 5: menuDate
                "\"RATING_MENU\" REAL," + // 6: ratingMenu
                "\"IMAGE_MENU\" BLOB);"); // 7: imageMenu
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LUNCH\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Lunch entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer principalMenuCode = entity.getPrincipalMenuCode();
        if (principalMenuCode != null) {
            stmt.bindLong(2, principalMenuCode);
        }
 
        Integer priceUnit = entity.getPriceUnit();
        if (priceUnit != null) {
            stmt.bindLong(3, priceUnit);
        }
 
        String mainMenuDescription = entity.getMainMenuDescription();
        if (mainMenuDescription != null) {
            stmt.bindString(4, mainMenuDescription);
        }
 
        Integer providerId = entity.getProviderId();
        if (providerId != null) {
            stmt.bindLong(5, providerId);
        }
 
        String menuDate = entity.getMenuDate();
        if (menuDate != null) {
            stmt.bindString(6, menuDate);
        }
 
        Double ratingMenu = entity.getRatingMenu();
        if (ratingMenu != null) {
            stmt.bindDouble(7, ratingMenu);
        }
 
        byte[] imageMenu = entity.getImageMenu();
        if (imageMenu != null) {
            stmt.bindBlob(8, imageMenu);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Lunch readEntity(Cursor cursor, int offset) {
        Lunch entity = new Lunch( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // principalMenuCode
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // priceUnit
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mainMenuDescription
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // providerId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // menuDate
            cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6), // ratingMenu
            cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7) // imageMenu
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Lunch entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPrincipalMenuCode(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setPriceUnit(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setMainMenuDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setProviderId(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setMenuDate(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRatingMenu(cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6));
        entity.setImageMenu(cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Lunch entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Lunch entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
