package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;
import java.security.SecureRandom;

/**
 * Entity mapped to table "LUNCH".
 */
public class Lunch implements Serializable{

    private Long id;
    private Integer principalMenuCode;
    private Integer priceUnit;
    private String mainMenuDescription;
    private Integer providerId;
    private String menuDate;
    private Double ratingMenu;
    private byte[] imageMenu;

    public Lunch() {
    }

    public Lunch(Long id) {
        this.id = id;
    }

    public Lunch(Long id, Integer principalMenuCode, Integer priceUnit, String mainMenuDescription, Integer providerId, String menuDate, Double ratingMenu, byte[] imageMenu) {
        this.id = id;
        this.principalMenuCode = principalMenuCode;
        this.priceUnit = priceUnit;
        this.mainMenuDescription = mainMenuDescription;
        this.providerId = providerId;
        this.menuDate = menuDate;
        this.ratingMenu = ratingMenu;
        this.imageMenu = imageMenu;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPrincipalMenuCode() {
        return principalMenuCode;
    }

    public void setPrincipalMenuCode(Integer principalMenuCode) {
        this.principalMenuCode = principalMenuCode;
    }

    public Integer getPriceUnit() {
        return priceUnit;
    }

    public void setPriceUnit(Integer priceUnit) {
        this.priceUnit = priceUnit;
    }

    public String getMainMenuDescription() {
        return mainMenuDescription;
    }

    public void setMainMenuDescription(String mainMenuDescription) {
        this.mainMenuDescription = mainMenuDescription;
    }

    public Integer getProviderId() {
        return providerId;
    }

    public void setProviderId(Integer providerId) {
        this.providerId = providerId;
    }

    public String getMenuDate() {
        return menuDate;
    }

    public void setMenuDate(String menuDate) {
        this.menuDate = menuDate;
    }

    public Double getRatingMenu() {
        return ratingMenu;
    }

    public void setRatingMenu(Double ratingMenu) {
        this.ratingMenu = ratingMenu;
    }

    public byte[] getImageMenu() {
        return imageMenu;
    }

    public void setImageMenu(byte[] imageMenu) {
        this.imageMenu = imageMenu;
    }

}
