package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "ORDER".
 */
public class Order implements Serializable{

    private Long id;
    private String orderType;
    private Integer statusOrder;
    private Long lunchId;
    private Integer drinkId;
    private Integer garnishId;
    private Long createdAt;
    private String SendAppAt;
    private Long providerId;
    private String orderAmount;
    private Long ratingLunch;
    private String user;
    private Integer transactionOrderId;
    private String observation;
    private String httpDetail;

    public Order() {
    }

    public Order(Long id) {
        this.id = id;
    }

    public Order(Long id, String orderType, Integer statusOrder, Long lunchId, Integer drinkId, Integer garnishId, Long createdAt, String SendAppAt, Long providerId, String orderAmount, Long ratingLunch, String user, Integer transactionOrderId, String observation, String httpDetail) {
        this.id = id;
        this.orderType = orderType;
        this.statusOrder = statusOrder;
        this.lunchId = lunchId;
        this.drinkId = drinkId;
        this.garnishId = garnishId;
        this.createdAt = createdAt;
        this.SendAppAt = SendAppAt;
        this.providerId = providerId;
        this.orderAmount = orderAmount;
        this.ratingLunch = ratingLunch;
        this.user = user;
        this.transactionOrderId = transactionOrderId;
        this.observation = observation;
        this.httpDetail = httpDetail;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderType() {
        return orderType;
    }

    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    public Integer getStatusOrder() {
        return statusOrder;
    }

    public void setStatusOrder(Integer statusOrder) {
        this.statusOrder = statusOrder;
    }

    public Long getLunchId() {
        return lunchId;
    }

    public void setLunchId(Long lunchId) {
        this.lunchId = lunchId;
    }

    public Integer getDrinkId() {
        return drinkId;
    }

    public void setDrinkId(Integer drinkId) {
        this.drinkId = drinkId;
    }

    public Integer getGarnishId() {
        return garnishId;
    }

    public void setGarnishId(Integer garnishId) {
        this.garnishId = garnishId;
    }

    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public String getSendAppAt() {
        return SendAppAt;
    }

    public void setSendAppAt(String SendAppAt) {
        this.SendAppAt = SendAppAt;
    }

    public Long getProviderId() {
        return providerId;
    }

    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    public String getOrderAmount() {
        return orderAmount;
    }

    public void setOrderAmount(String orderAmount) {
        this.orderAmount = orderAmount;
    }

    public Long getRatingLunch() {
        return ratingLunch;
    }

    public void setRatingLunch(Long ratingLunch) {
        this.ratingLunch = ratingLunch;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Integer getTransactionOrderId() {
        return transactionOrderId;
    }

    public void setTransactionOrderId(Integer transactionOrderId) {
        this.transactionOrderId = transactionOrderId;
    }

    public String getObservation() {
        return observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public String getHttpDetail() {
        return httpDetail;
    }

    public void setHttpDetail(String httpDetail) {
        this.httpDetail = httpDetail;
    }

}
