package tesis.com.py.sisgourmetmobile.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import tesis.com.py.sisgourmetmobile.entities.Order;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORDER".
*/
public class OrderDao extends AbstractDao<Order, Long> {

    public static final String TABLENAME = "ORDER";

    /**
     * Properties of entity Order.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OrderType = new Property(1, String.class, "orderType", false, "ORDER_TYPE");
        public final static Property StatusDescription = new Property(2, String.class, "statusDescription", false, "STATUS_DESCRIPTION");
        public final static Property StatusOrder = new Property(3, Integer.class, "statusOrder", false, "STATUS_ORDER");
        public final static Property DrinksId = new Property(4, Integer.class, "drinksId", false, "DRINKS_ID");
        public final static Property LunchId = new Property(5, Integer.class, "lunchId", false, "LUNCH_ID");
        public final static Property DrinkDetails = new Property(6, Integer.class, "drinkDetails", false, "DRINK_DETAILS");
        public final static Property LaunchDetails = new Property(7, Integer.class, "launchDetails", false, "LAUNCH_DETAILS");
        public final static Property CreatedAt = new Property(8, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property OrderAmount = new Property(9, Double.class, "orderAmount", false, "ORDER_AMOUNT");
    };


    public OrderDao(DaoConfig config) {
        super(config);
    }
    
    public OrderDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORDER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ORDER_TYPE\" TEXT," + // 1: orderType
                "\"STATUS_DESCRIPTION\" TEXT," + // 2: statusDescription
                "\"STATUS_ORDER\" INTEGER," + // 3: statusOrder
                "\"DRINKS_ID\" INTEGER," + // 4: drinksId
                "\"LUNCH_ID\" INTEGER," + // 5: lunchId
                "\"DRINK_DETAILS\" INTEGER," + // 6: drinkDetails
                "\"LAUNCH_DETAILS\" INTEGER," + // 7: launchDetails
                "\"CREATED_AT\" INTEGER," + // 8: createdAt
                "\"ORDER_AMOUNT\" REAL);"); // 9: orderAmount
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORDER\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Order entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String orderType = entity.getOrderType();
        if (orderType != null) {
            stmt.bindString(2, orderType);
        }
 
        String statusDescription = entity.getStatusDescription();
        if (statusDescription != null) {
            stmt.bindString(3, statusDescription);
        }
 
        Integer statusOrder = entity.getStatusOrder();
        if (statusOrder != null) {
            stmt.bindLong(4, statusOrder);
        }
 
        Integer drinksId = entity.getDrinksId();
        if (drinksId != null) {
            stmt.bindLong(5, drinksId);
        }
 
        Integer lunchId = entity.getLunchId();
        if (lunchId != null) {
            stmt.bindLong(6, lunchId);
        }
 
        Integer drinkDetails = entity.getDrinkDetails();
        if (drinkDetails != null) {
            stmt.bindLong(7, drinkDetails);
        }
 
        Integer launchDetails = entity.getLaunchDetails();
        if (launchDetails != null) {
            stmt.bindLong(8, launchDetails);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(9, createdAt.getTime());
        }
 
        Double orderAmount = entity.getOrderAmount();
        if (orderAmount != null) {
            stmt.bindDouble(10, orderAmount);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Order readEntity(Cursor cursor, int offset) {
        Order entity = new Order( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // orderType
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // statusDescription
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // statusOrder
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // drinksId
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // lunchId
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // drinkDetails
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // launchDetails
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)), // createdAt
            cursor.isNull(offset + 9) ? null : cursor.getDouble(offset + 9) // orderAmount
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Order entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrderType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStatusDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStatusOrder(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setDrinksId(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setLunchId(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setDrinkDetails(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setLaunchDetails(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setCreatedAt(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
        entity.setOrderAmount(cursor.isNull(offset + 9) ? null : cursor.getDouble(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Order entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Order entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
