package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSON".
 */
public class Person {

    private Long id;
    private String identyCard;
    private String ruc;
    private String name;
    private String lastName;
    private String locationAddress;
    private String privatePhone;
    private String mobilePhone;
    private String mailAddress;
    private Boolean nutritionalSatus;

    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    public Person(Long id, String identyCard, String ruc, String name, String lastName, String locationAddress, String privatePhone, String mobilePhone, String mailAddress, Boolean nutritionalSatus) {
        this.id = id;
        this.identyCard = identyCard;
        this.ruc = ruc;
        this.name = name;
        this.lastName = lastName;
        this.locationAddress = locationAddress;
        this.privatePhone = privatePhone;
        this.mobilePhone = mobilePhone;
        this.mailAddress = mailAddress;
        this.nutritionalSatus = nutritionalSatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentyCard() {
        return identyCard;
    }

    public void setIdentyCard(String identyCard) {
        this.identyCard = identyCard;
    }

    public String getRuc() {
        return ruc;
    }

    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getLocationAddress() {
        return locationAddress;
    }

    public void setLocationAddress(String locationAddress) {
        this.locationAddress = locationAddress;
    }

    public String getPrivatePhone() {
        return privatePhone;
    }

    public void setPrivatePhone(String privatePhone) {
        this.privatePhone = privatePhone;
    }

    public String getMobilePhone() {
        return mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    public String getMailAddress() {
        return mailAddress;
    }

    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    public Boolean getNutritionalSatus() {
        return nutritionalSatus;
    }

    public void setNutritionalSatus(Boolean nutritionalSatus) {
        this.nutritionalSatus = nutritionalSatus;
    }

}
