package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "PROVIDER_RATING".
 */
public class ProviderRating implements Serializable{

    private Long id;
    private Integer providerId;
    private String providerName;
    private Integer maxRating;
    private String providerRating;
    private Integer totalUserComments;
    private byte[] providerImage;
    private Integer fiveStar;
    private Integer fourStar;
    private Integer threeStar;
    private Integer twoStar;
    private Integer oneStar;

    public ProviderRating() {
    }

    public ProviderRating(Long id) {
        this.id = id;
    }

    public ProviderRating(Long id, Integer providerId, String providerName, Integer maxRating, String providerRating, Integer totalUserComments, byte[] providerImage, Integer fiveStar, Integer fourStar, Integer threeStar, Integer twoStar, Integer oneStar) {
        this.id = id;
        this.providerId = providerId;
        this.providerName = providerName;
        this.maxRating = maxRating;
        this.providerRating = providerRating;
        this.totalUserComments = totalUserComments;
        this.providerImage = providerImage;
        this.fiveStar = fiveStar;
        this.fourStar = fourStar;
        this.threeStar = threeStar;
        this.twoStar = twoStar;
        this.oneStar = oneStar;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getProviderId() {
        return providerId;
    }

    public void setProviderId(Integer providerId) {
        this.providerId = providerId;
    }

    public String getProviderName() {
        return providerName;
    }

    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    public Integer getMaxRating() {
        return maxRating;
    }

    public void setMaxRating(Integer maxRating) {
        this.maxRating = maxRating;
    }

    public String getProviderRating() {
        return providerRating;
    }

    public void setProviderRating(String providerRating) {
        this.providerRating = providerRating;
    }

    public Integer getTotalUserComments() {
        return totalUserComments;
    }

    public void setTotalUserComments(Integer totalUserComments) {
        this.totalUserComments = totalUserComments;
    }

    public byte[] getProviderImage() {
        return providerImage;
    }

    public void setProviderImage(byte[] providerImage) {
        this.providerImage = providerImage;
    }

    public Integer getFiveStar() {
        return fiveStar;
    }

    public void setFiveStar(Integer fiveStar) {
        this.fiveStar = fiveStar;
    }

    public Integer getFourStar() {
        return fourStar;
    }

    public void setFourStar(Integer fourStar) {
        this.fourStar = fourStar;
    }

    public Integer getThreeStar() {
        return threeStar;
    }

    public void setThreeStar(Integer threeStar) {
        this.threeStar = threeStar;
    }

    public Integer getTwoStar() {
        return twoStar;
    }

    public void setTwoStar(Integer twoStar) {
        this.twoStar = twoStar;
    }

    public Integer getOneStar() {
        return oneStar;
    }

    public void setOneStar(Integer oneStar) {
        this.oneStar = oneStar;
    }

}
