package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PROVIDER".
 */
public class Provider {

    private Long id;
    private Integer providerId;
    private String providerName;
    private byte[] providerImage;

    public Provider() {
    }

    public Provider(Long id) {
        this.id = id;
    }

    public Provider(Long id, Integer providerId, String providerName, byte[] providerImage) {
        this.id = id;
        this.providerId = providerId;
        this.providerName = providerName;
        this.providerImage = providerImage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getProviderId() {
        return providerId;
    }

    public void setProviderId(Integer providerId) {
        this.providerId = providerId;
    }

    public String getProviderName() {
        return providerName;
    }

    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    public byte[] getProviderImage() {
        return providerImage;
    }

    public void setProviderImage(byte[] providerImage) {
        this.providerImage = providerImage;
    }

}
