package tesis.com.py.sisgourmetmobile.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import tesis.com.py.sisgourmetmobile.entities.ProviderComments;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROVIDER_COMMENTS".
*/
public class ProviderCommentsDao extends AbstractDao<ProviderComments, Long> {

    public static final String TABLENAME = "PROVIDER_COMMENTS";

    /**
     * Properties of entity ProviderComments.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CommentId = new Property(1, Integer.class, "commentId", false, "COMMENT_ID");
        public final static Property CommentRating = new Property(2, Integer.class, "commentRating", false, "COMMENT_RATING");
        public final static Property CommentDescription = new Property(3, String.class, "commentDescription", false, "COMMENT_DESCRIPTION");
        public final static Property SelectedMenu = new Property(4, String.class, "selectedMenu", false, "SELECTED_MENU");
        public final static Property UserName = new Property(5, String.class, "userName", false, "USER_NAME");
        public final static Property DateComment = new Property(6, String.class, "dateComment", false, "DATE_COMMENT");
        public final static Property ProviderId = new Property(7, Integer.class, "providerId", false, "PROVIDER_ID");
    };


    public ProviderCommentsDao(DaoConfig config) {
        super(config);
    }
    
    public ProviderCommentsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROVIDER_COMMENTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"COMMENT_ID\" INTEGER," + // 1: commentId
                "\"COMMENT_RATING\" INTEGER," + // 2: commentRating
                "\"COMMENT_DESCRIPTION\" TEXT," + // 3: commentDescription
                "\"SELECTED_MENU\" TEXT," + // 4: selectedMenu
                "\"USER_NAME\" TEXT," + // 5: userName
                "\"DATE_COMMENT\" TEXT," + // 6: dateComment
                "\"PROVIDER_ID\" INTEGER);"); // 7: providerId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROVIDER_COMMENTS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ProviderComments entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer commentId = entity.getCommentId();
        if (commentId != null) {
            stmt.bindLong(2, commentId);
        }
 
        Integer commentRating = entity.getCommentRating();
        if (commentRating != null) {
            stmt.bindLong(3, commentRating);
        }
 
        String commentDescription = entity.getCommentDescription();
        if (commentDescription != null) {
            stmt.bindString(4, commentDescription);
        }
 
        String selectedMenu = entity.getSelectedMenu();
        if (selectedMenu != null) {
            stmt.bindString(5, selectedMenu);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(6, userName);
        }
 
        String dateComment = entity.getDateComment();
        if (dateComment != null) {
            stmt.bindString(7, dateComment);
        }
 
        Integer providerId = entity.getProviderId();
        if (providerId != null) {
            stmt.bindLong(8, providerId);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ProviderComments readEntity(Cursor cursor, int offset) {
        ProviderComments entity = new ProviderComments( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // commentId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // commentRating
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // commentDescription
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // selectedMenu
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // userName
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // dateComment
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7) // providerId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ProviderComments entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCommentId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setCommentRating(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCommentDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSelectedMenu(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUserName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDateComment(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setProviderId(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ProviderComments entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ProviderComments entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
