package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUALIFICATION".
 */
public class Qualification {

    private Long id;
    private Long providerId;
    private Long qualificationValue;
    private String commentary;
    private Long lunchId;
    private Long garnishId;

    public Qualification() {
    }

    public Qualification(Long id) {
        this.id = id;
    }

    public Qualification(Long id, Long providerId, Long qualificationValue, String commentary, Long lunchId, Long garnishId) {
        this.id = id;
        this.providerId = providerId;
        this.qualificationValue = qualificationValue;
        this.commentary = commentary;
        this.lunchId = lunchId;
        this.garnishId = garnishId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProviderId() {
        return providerId;
    }

    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    public Long getQualificationValue() {
        return qualificationValue;
    }

    public void setQualificationValue(Long qualificationValue) {
        this.qualificationValue = qualificationValue;
    }

    public String getCommentary() {
        return commentary;
    }

    public void setCommentary(String commentary) {
        this.commentary = commentary;
    }

    public Long getLunchId() {
        return lunchId;
    }

    public void setLunchId(Long lunchId) {
        this.lunchId = lunchId;
    }

    public Long getGarnishId() {
        return garnishId;
    }

    public void setGarnishId(Long garnishId) {
        this.garnishId = garnishId;
    }

}
