package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUALIFICATION".
 */
public class Qualification {

    private Long id;
    private String provider;
    private String qualification;
    private String commentary;

    public Qualification() {
    }

    public Qualification(Long id) {
        this.id = id;
    }

    public Qualification(Long id, String provider, String qualification, String commentary) {
        this.id = id;
        this.provider = provider;
        this.qualification = qualification;
        this.commentary = commentary;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getQualification() {
        return qualification;
    }

    public void setQualification(String qualification) {
        this.qualification = qualification;
    }

    public String getCommentary() {
        return commentary;
    }

    public void setCommentary(String commentary) {
        this.commentary = commentary;
    }

}
