package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUALIFICATION".
 */
public class Qualification {

    private Long id;
    private Long providerId;
    private Long qualificationValue;
    private String commentary;
    private String mainMenu;
    private String garnish;
    private Integer order;
    private Integer statusSend;
    private Long createdAt;
    private String SendAppAt;
    private String user;
    private String observation;
    private String httpDetail;

    public Qualification() {
    }

    public Qualification(Long id) {
        this.id = id;
    }

    public Qualification(Long id, Long providerId, Long qualificationValue, String commentary, String mainMenu, String garnish, Integer order, Integer statusSend, Long createdAt, String SendAppAt, String user, String observation, String httpDetail) {
        this.id = id;
        this.providerId = providerId;
        this.qualificationValue = qualificationValue;
        this.commentary = commentary;
        this.mainMenu = mainMenu;
        this.garnish = garnish;
        this.order = order;
        this.statusSend = statusSend;
        this.createdAt = createdAt;
        this.SendAppAt = SendAppAt;
        this.user = user;
        this.observation = observation;
        this.httpDetail = httpDetail;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProviderId() {
        return providerId;
    }

    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    public Long getQualificationValue() {
        return qualificationValue;
    }

    public void setQualificationValue(Long qualificationValue) {
        this.qualificationValue = qualificationValue;
    }

    public String getCommentary() {
        return commentary;
    }

    public void setCommentary(String commentary) {
        this.commentary = commentary;
    }

    public String getMainMenu() {
        return mainMenu;
    }

    public void setMainMenu(String mainMenu) {
        this.mainMenu = mainMenu;
    }

    public String getGarnish() {
        return garnish;
    }

    public void setGarnish(String garnish) {
        this.garnish = garnish;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Integer getStatusSend() {
        return statusSend;
    }

    public void setStatusSend(Integer statusSend) {
        this.statusSend = statusSend;
    }

    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public String getSendAppAt() {
        return SendAppAt;
    }

    public void setSendAppAt(String SendAppAt) {
        this.SendAppAt = SendAppAt;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getObservation() {
        return observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public String getHttpDetail() {
        return httpDetail;
    }

    public void setHttpDetail(String httpDetail) {
        this.httpDetail = httpDetail;
    }

}
