package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SUMMARY_ORDER".
 */
public class SummaryOrder {

    private Long id;
    private String orderDescription;
    private String garnishDescription;
    private String drinkDescription;
    private String date;
    private Integer year;
    private Integer month;
    private String price;
    private String provider;
    private byte[] image;
    private Long orderId;

    public SummaryOrder() {
    }

    public SummaryOrder(Long id) {
        this.id = id;
    }

    public SummaryOrder(Long id, String orderDescription, String garnishDescription, String drinkDescription, String date, Integer year, Integer month, String price, String provider, byte[] image, Long orderId) {
        this.id = id;
        this.orderDescription = orderDescription;
        this.garnishDescription = garnishDescription;
        this.drinkDescription = drinkDescription;
        this.date = date;
        this.year = year;
        this.month = month;
        this.price = price;
        this.provider = provider;
        this.image = image;
        this.orderId = orderId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderDescription() {
        return orderDescription;
    }

    public void setOrderDescription(String orderDescription) {
        this.orderDescription = orderDescription;
    }

    public String getGarnishDescription() {
        return garnishDescription;
    }

    public void setGarnishDescription(String garnishDescription) {
        this.garnishDescription = garnishDescription;
    }

    public String getDrinkDescription() {
        return drinkDescription;
    }

    public void setDrinkDescription(String drinkDescription) {
        this.drinkDescription = drinkDescription;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

}
