package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRANSACTION".
 */
public class Transaction {

    private Long id;
    private java.util.Date createDateAt;
    private String description;
    private Integer transactionAmount;

    public Transaction() {
    }

    public Transaction(Long id) {
        this.id = id;
    }

    public Transaction(Long id, java.util.Date createDateAt, String description, Integer transactionAmount) {
        this.id = id;
        this.createDateAt = createDateAt;
        this.description = description;
        this.transactionAmount = transactionAmount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getCreateDateAt() {
        return createDateAt;
    }

    public void setCreateDateAt(java.util.Date createDateAt) {
        this.createDateAt = createDateAt;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getTransactionAmount() {
        return transactionAmount;
    }

    public void setTransactionAmount(Integer transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

}
