package tesis.com.py.sisgourmetmobile.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USERS".
 */
public class Users {

    private Long id;
    private String userName;
    private String password;
    private Boolean userStatus;
    private String identifyCardNumber;

    public Users() {
    }

    public Users(Long id) {
        this.id = id;
    }

    public Users(Long id, String userName, String password, Boolean userStatus, String identifyCardNumber) {
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.userStatus = userStatus;
        this.identifyCardNumber = identifyCardNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getUserStatus() {
        return userStatus;
    }

    public void setUserStatus(Boolean userStatus) {
        this.userStatus = userStatus;
    }

    public String getIdentifyCardNumber() {
        return identifyCardNumber;
    }

    public void setIdentifyCardNumber(String identifyCardNumber) {
        this.identifyCardNumber = identifyCardNumber;
    }

}
